enum SidraLocalidades {
    N1 = 'Pais',
    N2 = 'Grande Região',
    N3 = 'Unidade da Federação',
    N6 = "Município",
    N7 = "Região Metropolitana",
    N8 = "Mesorregião Geográfica",
    N9 = "Microrregião Geográfica",
    N10 = "Distrito",
    N11 = "Subdistrito",
    N13 = "Região Metropolitana e Subdivisão",
    N14 = "Região Integrada de Desenvolvimento",
    N15 = "Aglomeração Urbana",
    N17 = "Aglomerado Subnormal",
    N18 = "Área de Ponderação",
    N19 = "Área de Ponderação Recalculada",
    N23 = "Arranjo Populacional",
    N102 = "Bairro",
    N104 = "Argentina",
    N105 = "Uruguai",
    N106 = "Paraguai",
    N129 = "Território da Cidadania"
}